### ISSUE TITLE
Contribution à la cartographie

### ISSUE THREAD

**Issue by claustres** [opencovid19-fr/comment-contribuer#1]
Est-il possible de rajouter un lien vers notre dépôt https://github.com/kalisio/covid-19 ?

Si oui souhaitez-vous une PR ?

Merci

**Comment by bzg** [comment]
Oui, je le fais - est-ce qu'il y a une URL à indiquer pour voir une ou des représentations carto/graphiques ?

**Comment by claustres** [comment]
Le dépôt contient une vidéo et des exemples de visu mais pour l'instant nous n'avons pas mis de site en ligne, peut être dans le futur.

Merci

**Comment by bzg** [comment]
Ok, c'est fait, merci !
