### ISSUE TITLE
Lien d'invitation Slack inactif

### ISSUE THREAD

**Issue by P-Bouche** [opencovid19-fr/comment-contribuer#2]
Bonjour,

Le lien d'invitation au Slack mentionné dans le readme est n'est plus actif. Est-ce car il n'est plus d'actualité ou y en a-t-il un nouveau ?

**Comment by bzg** [comment]
Hello ! [Ce lien](https://join.slack.com/t/dataagainstcovid-19/shared_invite/zt-cgsplso2-LIvWeRHlf1ZFIrh~SPj~IA) est toujours valide de mon côté - mais je suis déjà dans ce slack - peut-être que l'invitation publique a été annulée ?

Peux-tu confirmer que le lien ne fonctionne pas ? Qu'as-tu à la place de l'invitation ?

**Comment by P-Bouche** [comment]
Je te confirme que ça ne fonctionne pas. J'arrive sur une page avec l'erreur suivante :

<img width="347" alt="Capture" src="https://user-images.githubusercontent.com/41999853/80962015-7f04e380-8e0c-11ea-849c-5e1309700a81.PNG">

**Comment by bzg** [comment]
Merci pour la confirmation - j'ai mis à jour le lien avec [celui-ci](https://join.slack.com/t/dataagainstcovid-19/shared_invite/zt-e1ttv9o3-b5rCLcK3lqu3zcFMrJIBdg).
